### ISSUE TITLE
Client shows wrong symbols in dictionary entries

### ISSUE THREAD

**Issue by andry-tino** [Slevinski/apitxt#1]
### Configuration
- Chrome or Firefox latest version
- MacOS Mojave latest
- OS set in English

### Repro
When selecting the US language in the client and searching at [this url](https://signpuddle.com/client/#!/dictionary/ase-US-dictionary-public/search), the following appears:

![image](https://user-images.githubusercontent.com/6501517/59636244-566fee80-9153-11e9-8d59-1a4cc93c2b60.png)

The SignWriting symbols do not appear correctly :(

---

### More info
The F12 console does not show any error.

**Comment by Slevinski** [comment]
Thanks for the report.  I used the relative font-face declaration in the file "client/include/common.css", rather than the absolute.  The font-face declarations are used to install the fonts in the browser cache if the fonts haven't been installed on the user's system.  I will have this updated for the beta by the end of this week.

In the meantime, you can install the fonts on your system if you like.  You can find full instructions here: https://slevinski.github.io/SuttonSignWriting/components/fonts.html

You'll want the Sutton SignWriting Line, Sutton SignWriting Fill, and Sutton SignWriting One D fonts.

**Comment by andry-tino** [comment]
Thanks, the workaround of installing them worked 😄

**Comment by andry-tino** [comment]
One question: Take the sign for D handshape:

![image](https://user-images.githubusercontent.com/6501517/59870965-c7531880-9396-11e9-941a-8c2565496ae9.png)

What is the final UTF-32 code? How do I build it?

**Comment by andry-tino** [comment]
One more sorry eheh.

The same D shape, but done with the other hand, is the following right?

![image](https://user-images.githubusercontent.com/6501517/59871082-01bcb580-9397-11e9-8e0f-bcb2cc6adc72.png)

So I can assume that there are signs specific for the right hand and the left hand? Like this I know what I need to remove from the temporal sequence to filter out the data of the non-dominant hand...

Thanks

**Comment by Slevinski** [comment]
If you hover over the symbol, it will give you the UTF-32 code.

Or you can cross-reference the column and row with the starting value.

In the first graphic, the starting point is U+40001.  For the first symbol is column +0 and row +0.  So the code point is U+40001.

The second graphic is still column +0, but row +8.  The same starting point, so the code point is U+40009.

With signs written from the signer's perspective, the first symbol would be the right hand and the second would be the left hand.

However, you can not assume that the top is always right and the bottom is always left.  Take for example the symbol is column +10 and row +8.  This would have a code point of U+40019.
![Screen Shot 2019-06-20 at 4 05 51 PM](https://user-images.githubusercontent.com/376945/59881557-85fe4100-9375-11e9-80ec-095303e73496.png)

This hand can be either left or right.  For certain hand shapes and fills and positions, the left and right hands can use the same symbol.
![Screen Shot 2019-06-20 at 4 09 21 PM](https://user-images.githubusercontent.com/376945/59881731-e68d7e00-9375-11e9-9665-00791e72a507.png)

I did a quick search for signs using U+40001 and signs using U+40008.  There is some overlap of the signs, but not all.  Just to illustrate some of the signs in question.
![Screen Shot 2019-06-20 at 4 14 21 PM](https://user-images.githubusercontent.com/376945/59881991-a67acb00-9376-11e9-9847-e4b315c2daed.png)

**Comment by andry-tino** [comment]
@Slevinski I think this issue should relate only to the fonts not properly displayed as per the beginning on the conversation. So please close this issue when the problem has been fixed on all browsers and OSs 😄  Thank you

**Comment by Slevinski** [comment]
The fonts are now included in the project and the css has been updated appropriately.
