### ISSUE TITLE
Where can I find the Unicode sheet for all symbols in FSW/USW?

### ISSUE THREAD

**Issue by andry-tino** [Slevinski/apitxt#3]
I am struggling to find the latest version of the Unicode sheet reporting **all** symbols' codes.

### Reason
I am conducting a research where I need to strip, from every sign in a limited set (300 most used signs), the information about the non-dominant hand from the temporal sequence.

In order to do that I need to complete sheet of symbols in SW so I know where I can remove what from the sequence.

Thanks

**Comment by Slevinski** [comment]
The SignWriting Character Viewer shows all of the SignWriting Characters.
http://slevinski.github.io/SignWriting_Character_Viewer/SignWriting_Character_Viewer_2.html

If you need something else, I can quickly create something for you.  Just let me know what you need.

The characters of SignWriting in Unicode (SWU) have been submitted to the UTC, but they are not part of the official Unicode standard.
http://unicode.org/L2/L2017/17220-signwriting-design-opt.pdf

The officially accepted characters for SignWriting were added to Unicode 8, but they are not usable in their current form.
https://www.slideshare.net/StephenSlevinski/sign-writing-in-unicode-8-issues

**Comment by andry-tino** [comment]
Even though I have installed the fonts, I get this:

![image](https://user-images.githubusercontent.com/6501517/59869808-82c67d80-9394-11e9-9f50-3af107fe3bc7.png)

And thanks for your availability as always 😄

**Comment by andry-tino** [comment]
I can verify that I have the fonts installed because I can use SignPuddle and I can see the symbols there:

![image](https://user-images.githubusercontent.com/6501517/59870064-0a13f100-9395-11e9-8ef0-6d9e73f24cc4.png)

Same browser window!

**Comment by Slevinski** [comment]
Mac is more forgiving.  I need to add some CSS to define the font family for the divs.

**Comment by andry-tino** [comment]
I am actually on Windows, so if I try there on Mac it should work? I will give it a try...

**Comment by Slevinski** [comment]
I will be able to update the viewer later today.

**Comment by andry-tino** [comment]
Thanks, it actually works on Mac 😄
