### ISSUE TITLE
Distinguishing left and right hands in SignWriting

### ISSUE THREAD

**Issue by andry-tino** [Slevinski/apitxt#4]
Since this is a question on its own, I am creating a different thread where we can share thoughts on this regard.

### Original answer
If you hover over the symbol, it will give you the UTF-32 code.

Or you can cross-reference the column and row with the starting value.

In the first graphic, the starting point is U+40001.  For the first symbol is column +0 and row +0.  So the code point is U+40001.

The second graphic is still column +0, but row +8.  The same starting point, so the code point is U+40009.

With signs written from the signer's perspective, the first symbol would be the right hand and the second would be the left hand.

However, you can not assume that the top is always right and the bottom is always left.  Take for example the symbol is column +10 and row +8.  This would have a code point of U+40019.
![Screen Shot 2019-06-20 at 4 05 51 PM](https://user-images.githubusercontent.com/376945/59881557-85fe4100-9375-11e9-80ec-095303e73496.png)

This hand can be either left or right.  For certain hand shapes and fills and positions, the left and right hands can use the same symbol.
![Screen Shot 2019-06-20 at 4 09 21 PM](https://user-images.githubusercontent.com/376945/59881731-e68d7e00-9375-11e9-9665-00791e72a507.png)

I did a quick search for signs using U+40001 and signs using U+40008.  There is some overlap of the signs, but not all.  Just to illustrate some of the signs in question.
![Screen Shot 2019-06-20 at 4 14 21 PM](https://user-images.githubusercontent.com/376945/59881991-a67acb00-9376-11e9-9847-e4b315c2daed.png)

_Originally posted by @Slevinski in https://github.com/Slevinski/apitxt/issues/1#issuecomment-504191385_

**Comment by andry-tino** [comment]
So there is basically no way to extract the information on the non-dominant hand (assumed: left) from the Time Sequence in an automated way? Since the time sequence was created mainly to target analysis, wouldn't it be useful to have some sort of convention on the hands?

**Comment by andry-tino** [comment]
Also, when reading SignWriting, the symbols refer to the signer or the receiver? In the presentation it is mentioned that Sutton initially created the system to refer to the POV of the receiver but that later was changed in favor of the signer after getting more feedback from the community.

So the signs I see in the sequences, are they from the POV of the signer? It does not look like it...

**Comment by Slevinski** [comment]
I do think you can use the time sequence to extract the information you require.  However, these dictionaries are created by the public so they may not always be consistent.  Later this year, we'll be starting an initiative to clean up and standardize the dictionaries using SignPuddle 3.

Signs can be written from either POV and they can be written left-hand dominant or right-hand dominant.  Most writing is from the signer's POV as expressive.
