### ISSUE TITLE
Error starting SignPuddle 3 Portable System

### ISSUE THREAD

**Issue by bidaian** [Slevinski/apitxt#5]
After following the [README](https://github.com/Slevinski/apitxt/tree/master/system), the requests fail with this message:

```
$ ./start_system.sh 
./start_system.sh: línea 1: ifconfig: no se encontró la orden
PHP 7.0.33-0+deb9u3 Development Server started at Tue Jul  2 14:54:07 2019
Listening on http://0.0.0.0:8888
Document root is /tmp/apitxt
Press Ctrl-C to quit.
[Tue Jul  2 14:54:12 2019] PHP Warning:  Unknown: failed to open stream: No such file or directory in Unknown on line 0
[Tue Jul  2 14:54:12 2019] PHP Fatal error:  Unknown: Failed opening required '/tmp/apitxt/rewrite.php' (include_path='.:/usr/share/php') in Unknown on line 0
```

**Comment by Slevinski** [comment]
Thanks for the report.  I see that you were able to resolve this issue.

I am unable to reproduce this issue on Windows, Mac, or Linux mint.  The start_system.sh works as intended.  PHP versions 5.4, 7.1, and 7.2.  I am not sure why you needed to append the subdirectory and why I don't.  Searching the PHP documentation didn't help.

Additionally, I still need to add some details to the SignPuddle 3 setup.  Please report any questions or issues.

**Comment by bidaian** [comment]
Have you tried with a clean clone? (I'm Linux, Debian 9, PHP 7). Anyway, it's not that big of an issue, maybe I skipped one of the preparations steps. Feel free to close it.

By the way, it does not happen at start up, you have to visit the page ( http://0.0.0.0:8888) to get the error.

**Comment by Slevinski** [comment]
Yeah, I created a fresh clone on Linux Mint and it worked fine.  I'll make a note in the documentation about this potential issue.
